version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: on-failure
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dong14052004  
      MYSQL_DATABASE: social-website          
      MYSQL_USER: user                  
      MYSQL_PASSWORD: password          
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build: .
    image: social-website  
    container_name: social-website-app 
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_container:3306/social-website?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dong14052004
    depends_on:
      - mysql
      - redis
    networks:
      - app_network

  redis:
    image: redis/redis-stack-server:latest
    container_name: my_redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
